# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  # Angular
  - port: 4200
    onOpen: notify
# MongoDb
  - port: 27017
    onOpen: notify
# Api Node Express
  - port: 3000
    onOpen: notify

# Tarefas na Inicialização
tasks:
  - before: export NG_CLI_ANALYTICS=ci
  - init: echo n | npm i -g @angular/cli jshint typescript-eslint
  - command: >
        mkdir -p /workspace/data && 
        mongod --dbpath /workspace/data
  - command: >
      cd ./aplicacao-web &&
      npm install
  - command: >
      cd ./servidor-api &&
      npm install
  - command: >
      gp await-port 4200 && gp preview $(gp url 4200)web/ && gp forward-port 4200
      gp await-port 3000 && gp preview $(gp url 3000)api/ && gp forward-port 3000
      

# Github
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false

# Extensões VSCode
vscode:
  extensions:
    - mongodb.mongodb-vscode@0.5.0:f041958ce98090c95ed79a8a75b69c00
    - mikael.angular-beastcode@10.0.3:449d9b32ebd4a40b83eb70f9a2c28732
    - ecmel.vscode-html-css@1.9.1:23103121f682e8e5bbd2f7e5e55c8a6e
    - esbenp.prettier-vscode@6.3.2:13e527ae62035854197198eedd2bc84f