# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  # Angular
  - port: 4200
    onOpen: ignore
# MongoDb
  - port: 27017
    onOpen: ignore
# Api Node Express
  - port: 9000
    onOpen: ignore

# Tarefas na Inicialização
tasks:
  - before: export NG_CLI_ANALYTICS=ci
  - init: echo n | npm i -g @angular/cli jshint typescript-eslint
  - command: >
        mkdir -p /workspace/data && 
        mongod --dbpath /workspace/data &&
        gp await-port 27017 &&
        gp forward-port 27017
  - command: >
      cd ./aplicacao-web &&
      npm install &&
      npm run start-web &&
      gp await-port 4200 &&
      gp forward-port 4200
  - command: >
      cd ./servidor-api &&
      npm install &&
      npm run start-api &&
      gp await-port 9000 &&
      gp forward-port 9000
  - command: >
      cd ./servidor-api &&
      gp await-port 27017 &&
      gp await-port 9000 &&
      sleep 12 &&
      npm run start-data

# Github
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false

# Extensões VSCode
vscode:
  extensions:
    - mongodb.mongodb-vscode@0.5.0:f041958ce98090c95ed79a8a75b69c00
    - mikael.angular-beastcode@10.0.3:449d9b32ebd4a40b83eb70f9a2c28732
    - ecmel.vscode-html-css@1.9.1:23103121f682e8e5bbd2f7e5e55c8a6e
    - esbenp.prettier-vscode@6.3.2:13e527ae62035854197198eedd2bc84f