# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - port: 4200
    onOpen: open-preview
  - port: 27017
    onOpen: ignore

# Tarefas na Inicialização
tasks:
  - before: export NG_CLI_ANALYTICS=ci
  - init: echo n | npm i -g @angular/cli
  - command: >
        npm install -g jshint typescript-eslint
  - command: >
        mkdir -p /workspace/data && 
        mongod --dbpath /workspace/data
        sleep 6 &&
        mongodb://localhost:27017/?readPreference=primary&appname=mongodb-vscode%200.5.0&ssl=false &&
        mongo &&
        show dbs &&
        use authentication
  - command: >
      cd ./aplicacao-web &&
      npm install
      sleep 6 &&
      ng serve --host 0.0.0.0 --disableHostCheck
  - command: >
      cd ./servidor-api &&
      npm install

# Github
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false

# Extensões VSCode
vscode:
  extensions:
    - mongodb.mongodb-vscode@0.5.0:f041958ce98090c95ed79a8a75b69c00
    - dracula-theme.theme-dracula@2.22.3:736ab1bad936c53fd45bc2fdfbd6d6da
    - mikael.angular-beastcode@10.0.3:449d9b32ebd4a40b83eb70f9a2c28732
    - ecmel.vscode-html-css@1.9.1:23103121f682e8e5bbd2f7e5e55c8a6e
    - esbenp.prettier-vscode@6.3.2:13e527ae62035854197198eedd2bc84f
    - tabnine.tabnine-vscode@3.2.17:16841d6c91c484eaeb3e800aedbc99fe
    - richie5um2.vscode-sort-json@1.20.0:489466c0f3b034010814e86465d989b6